DROP TABLE IF EXISTS "film_genres" CASCADE;
DROP TABLE IF EXISTS "friendship" CASCADE;
DROP TABLE IF EXISTS "genres" CASCADE;
DROP TABLE IF EXISTS "likes" CASCADE;
DROP TABLE IF EXISTS "films" CASCADE;
DROP TABLE IF EXISTS "rating_mpa" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

CREATE TABLE IF NOT EXISTS "films" (
                                       "film_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                       "rating_id" BIGINT NOT NULL,
                                       "name" VARCHAR(200) NOT NULL,
                                       "description" VARCHAR(200),
                                       "release_date" DATE NOT NULL,
                                       "length" INT NOT NULL,
                                       "rate" INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "rating_mpa" (
                                            "rating_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            "name" VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "genres" (
                                            "genre_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                            "name" VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "film_genres" (
                                                 "film_id" BIGINT NOT NULL,
                                                 "genre_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
                                       "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                       "email" VARCHAR(200) UNIQUE NOT NULL,
                                       "login" VARCHAR(200) UNIQUE NOT NULL,
                                       "name" VARCHAR(200) NOT NULL,
                                       "birthday" DATE
);

CREATE TABLE IF NOT EXISTS "friendship" (
                                            "user_id" BIGINT NOT NULL,
                                            "friend_id" BIGINT NOT NULL,
                                            "status" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "likes" (
                                       "film_id" BIGINT NOT NULL,
                                       "user_id" BIGINT NOT NULL,
                                       "date" DATE NOT NULL,
                                       PRIMARY KEY ("film_id", "user_id")
);

ALTER TABLE "films" DROP CONSTRAINT IF EXISTS "fk_films_rating_id";
ALTER TABLE "film_genres" DROP CONSTRAINT IF EXISTS "fk_films_genres_film_id";
ALTER TABLE "film_genres" DROP CONSTRAINT IF EXISTS "fk_film_genres_genres_id";
ALTER TABLE "friendship" DROP CONSTRAINT IF EXISTS "fk_friendship_user_id";
ALTER TABLE "friendship" DROP CONSTRAINT IF EXISTS "fk_friendship_friend_id";
ALTER TABLE "likes" DROP CONSTRAINT IF EXISTS "fk_likes_film_id";
ALTER TABLE "likes" DROP CONSTRAINT IF EXISTS "fk_likes_user_id";

ALTER TABLE "films" ADD CONSTRAINT "fk_films_rating_id" FOREIGN KEY ("rating_id") REFERENCES "rating_mpa" ("rating_id");
ALTER TABLE "film_genres" ADD CONSTRAINT "fk_films_genres_film_id" FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");
ALTER TABLE "film_genres" ADD CONSTRAINT "fk_film_genres_genres_id" FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id");
ALTER TABLE "friendship" ADD CONSTRAINT "fk_friendship_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
ALTER TABLE "friendship" ADD CONSTRAINT "fk_friendship_friend_id" FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id");
ALTER TABLE "likes" ADD CONSTRAINT "fk_likes_film_id" FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");
ALTER TABLE "likes" ADD CONSTRAINT "fk_likes_user_id" FOREIGN KEY  ("user_id") REFERENCES "users"  ("user_id");
